### PR TITLE
added some new landmarks

### PR DESCRIPTION
**Pull request by AndrewP1179**

### CODE REVIEW

**Review by pascalbenschopTU — CHANGES_REQUESTED** [review]
Please scale all assets accordingly, so the landmarks need to be of same size
Also assets in the alien / desert scene need to be rescaled, plants are too small

**Comment by AndrewP1179** [comment]
fixed everything

**Comment by pascalbenschopTU** [comment]
Only merge conflicts left

**Comment by AndrewP1179** [comment]
fixed conflicts

**Pull request merged**
